### ISSUE TITLE
WPE - process crashed

### ISSUE THREAD

**Issue by koff75** [idoodler/balena-MagicMirror#1]
Hey :)

I tried on a Raspberry pi 3 with a RESIN_HOST_CONFIG_gpu_mem of 396.

I have a loop on the Browser container :
```
WARNING: WebProcess crashed: restarting it ...
failed to add service - already in use?
```

If you have an idea of where comes this issue...
Thanks :)

**Comment by idoodler** [comment]
@koff75 Sorry for the late response, I missed your entry:/

Did you modify the `docker-compose.yml` in any way?

I also encourage you to update the project I fixed a lot of issues regarding stability;)

**Comment by idoodler** [comment]
@koff75 Ping

**Comment by koff75** [comment]
I updated the project with your last code and customize the docker-compose.xml. It's working well, thanks for your response. :)
